[package]
name = "day25"
version = "0.1.0"
authors = ["stanciua <andrei.stanciu@aciworldwide.com>"]


[dependencies.nom]
version = "3.2.1"
features = ["nightly"]

[dependencies]
pretty_assertions = "0.5.1"
lazy_static = "*"